name: FactionsPro
author: Tethered_ & Awzaw
description: A Plugin For Easily Managing Factions
version: 1.3.7.AWZ
main: FactionsPro\FactionMain
api: [2.0.0, 3.0.0-ALPHA1]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"