name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.10-dev2
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA7]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"