name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.18
main: FactionsPro\FactionMain
api: [3.0.0]
softdepend: ["PureChat", "AntiSpamPro"]
extensions: [sqlite3]
commands:
  f:
    description: use /f help for all parameter
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
