name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [beta Branch]
version: 3.0.0-BETA
main: FactionsPro\FactionMain
api: 4.0.0
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI", "TeaSpoon"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
